version: '3.8'

services:
  express-app:
    build: .
    ports:
      - "3000:3000"  # Maps host:container port
    environment:
      - PORT=3000  
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - express-app
    restart: unless-stopped